---
title: 2023 honours multivariate FA practical
format:
  pdf:
    embed-resources: true
    include-in-header:
      - text: |
          \usepackage{unicode-math}
          \usepackage{mathpazo}
    keep-tex: true
---

## Question One (4)

Show that the covariance matrix 

$$
\symbf{\rho} = 
\begin{bmatrix}
1 & 0.63 & 0.45 \\
0.63 & 1 & 0.35 \\
0.45 & 0.35 & 1 
\end{bmatrix}
$$


for the $p=3$ standardised random variables $Z_1$, $Z_2$ and $Z_3$ can be generated by the $m=1$ factor model 

\begin{align*}
Z_1 &= 0.9F_1 + \epsilon_1 \\
Z_2 &= 0.7F_1 + \epsilon_2 \\
Z_3 &= 0.5F_1 + \epsilon_3
\end{align*}


where $\mathrm{Var}[F_1]=1$, $\mathrm{Cov}[\symbf{\epsilon}, F_1]=\symbf{0}$ and 

$$
\symbf{\Psi} = \mathrm{Cov}[\symbf{\epsilon}] = 
\begin{bmatrix}
0.19 & 0 & 0 \\
0 & 0.51 & 0 \\
0 & 0 & 0.75 
\end{bmatrix}.
$$

That is, write $\symbf{\rho}$ in the form $\symbf{L}\symbf{L}' + \symbf{\Psi}$, where $\symbf{L}$ is the matrix of loadings and $\symbf{\Psi}$ is the diagonal matrix of specific variances.

## Question Two (13)

Use the air pollution data stored in `Air Polution Data.csv`.

a. Generate a sample correlation matrix. (1)
b. Obtain the principal component solution to a factor model with $m=1$ and $m=2$ using the `eigen` function (as before, you must use the `eigen` function). (3)
d. Obtain the maximum likelihood factor model for $m=2$ using `factanal`. (2)
e. Compare the factorization obtained by the principal component and maximum likelihood methods. (2)
f. Perform a varimax rotation of the principal component solution with $m=2$ factors. Interpret the results. (3)
g. Calculate the factor scores from the m=2 maximum likelihood approach using weighted least squares (i.e. using the matrix formula for the factor scores). (2)

## Question Three (4)

In FA we are concerned with accurately capturing the covariance of the variables. 
In this question we prove an upper bound for the sum of squared errors between our fitted covariance matrix and the sample covariance matrix, when we use the principal component method. 

For $\symbf{S}:p\times p$ the sample covariance matrix, $\hat{\symbf{L}}:p\times m$ the matrix of loadings estimated using the principal component method and $\hat{\symbf{\Psi}}$ the diagonal matrix of specific variances, show that 

$$
\mathrm{tr}[(\symbf{S}-(\hat{\symbf{L}}\hat{\symbf{L}}' + \hat{\symbf{\Psi}}))'(\symbf{S}-(\hat{\symbf{L}}\hat{\symbf{L}}' + \hat{\symbf{\Psi}}))]\leq \sum_{i=m+1}^p\lambda_i^2.
$$

In other words, show that the sum of squared errors between the sample covariance matrix and the fitted covariance matrix is upper bounded by the sum of the squared eigenvalues of unused principal components.

- Note that $\symbf{S}-(\hat{\symbf{L}}\hat{\symbf{L}}' + \hat{\symbf{\Psi}})$ has zeroes on the diagonal, meaning that $\mathrm{tr}[(\symbf{S}-(\hat{\symbf{L}}\hat{\symbf{L}}' + \hat{\symbf{\Psi}}))'(\symbf{S}-(\hat{\symbf{L}}\hat{\symbf{L}}' + \hat{\symbf{\Psi}}))]\leq \mathrm{tr}[(\symbf{S}-\hat{\symbf{L}}\hat{\symbf{L}}')'(\symbf{S}-\hat{\symbf{L}}\hat{\symbf{L}}')]$
- Also note that $\symbf{S}-\hat{\symbf{L}}\hat{\symbf{L}}'=\sum_{i=m+1}^p\lambda_i\symbf{e}_i\symbf{e}_i'$, where $\symbf{e}_i$ is the eigenvector of $\symbf{S}$ associated with the $i$-th largest eigenvalue $\lambda_i$.
- The trace property that $\mathrm{tr}[\symbf{A}\symbf{B}\symbf{C}]=\mathrm{tr}[\symbf{C}\symbf{A}\symbf{B}]=\mathrm{tr}[\symbf{B}\symbf{C}\symbf{A}]$ and the transpose property that $\symbf{A}\symbf{B})'=\symbf{B}'\symbf{A}'$ are useful here. 
  
